### ISSUE TITLE
consider giving a config option to flush storage on every block

### ISSUE THREAD

**Issue by tzemanovic** [anoma/anoma#372]
We should consider giving a config option to flush storage on every block. Right now, it writes to memtable and only flushes on a clean shutdown.

Maybe the default should be to always flush as it's the safer option.

**Comment by yito88** [comment]
I think the data on the memtable can be protected by enabling WAL, instead of flush.

- Disable WAL(write into only the memtable) [now]
  - No disk write
  - Lose data on memtable when shutting the node down suddenly
    - Need to recover the data from another node

- Enable WAL (write into the memtable and disk)
  - DIsk write (small, sequential)
  - The data on the memtable is recovered when RocksDB restarts

- Always flush
  - Disk write
  - Frequent compactions
  - All data on the disk

**Comment by tzemanovic** [comment]
To avoid issues with wrong root hash, I think we should set `cf_opts.set_atomic_flush(true)` and enable WAL
