### ISSUE TITLE
Add option to print intent to stdout

### ISSUE THREAD

**Issue by Fraccaman** [anoma/anoma#405]
It would be nice to be able to log the intent output to stdout and not only to file

**Comment by tzemanovic** [comment]
We currently have 2 commands for intent, one to `craft-intent` into a file and `intent` to submit it from a file to a gossiper's RPC. To simplify this, we can remove the `craft-intent` commands and add an argument (e.g. `--to-stdout` (`-O`)) that will print an intent to stdout. From there, one can redirect it to a file with `>`/`>>`.

Additionally, let's add this option to tx commands to, for which we can output the raw txs instead of submitting them to a node.

**Comment by tzemanovic** [comment]
#417 implemented the `--stdout` option. Next, we should add a way to submit an intent from a file, e.g. something like:

```shell
1.
# write a signed intent into a file
anoma intent --raw-intent intent.B.data --key a1qq5qqqqqxv6yydz9xc6ry33589q5x33eggcnjs2xx9znydj9xuens3phxppnwvzpg4rrqdpswve4n9 --stdout > signed_intent.data

# submit the intent from the file to the RPC
anoma intent --node "http://127.0.0.1:39112" --topic "asset_v1" --intent-path signed_intent.data

2.
# write an un-signed intent into a file (when no key is specified
anoma intent --raw-intent intent.B.data --stdout > unsigned_intent.data

# sign and submit the intent from the file to the RPC
anoma intent --node "http://127.0.0.1:39112" --topic "asset_v1" --key a1qq5qqqqqxv6yydz9xc6ry33589q5x33eggcnjs2xx9znydj9xuens3phxppnwvzpg4rrqdpswve4n9 --intent-path unsigned_intent.data
```
```

We should also add the `--stdout` flag to tx commands. Similarly, we can output the tx data to stdout (signed or unsinged), instead of submitting it to the ledger's mempool and allow to submit a tx from a file.
