### ISSUE TITLE
Retry Policies in the DKG

### ISSUE THREAD

**Issue by batconjurer** [anoma/anoma#672]
In participating in the DKG, several rounds of messages containing PVSS transcripts should land on-chain and certain thresholds should be met. In order to maximize the chances of success, we should have retry policies regarding messages sent by validators. 

PVSS transcripts are large in size, so we adopt a scheduling routine to stagger messages. We have 2^7 validators at maximum. We also have a canonical ordering of the active set that all validators are aware of (this is done in the the DKG state machine). 

We define a `window` as 32 blocks. Validators will split into 8 sets of of 16 each via the canonical ordering. The sets are naturally ordered as well and get their own `window`. Validators only announce PVSS transcripts during their `window`. If their PVSS transcript does not land on-chain during their `window`, or in `window + 1`, they reissue in `window+2`.

All of this continues until the threshold of 2/3+1 validators by weight have dealt.  The mempool should reject PVSS transcripts once this happens as an optimization. 

 - [x] Change DKG Validator input to include their session keys
 - [x] Changed the Shared state to include the PVSS transcript of dealer and a substate that tracks when to reissue

**Comment by joebebel** [comment]
I think it's safer to handle session keys outside of the DKG, where:
1. When a validator registers to become a validator (at all) they include their first session key
2. Session keys persist between epochs, until they are updated by the validator, anytime. A validator can choose to update once epoch (becoming effective the next DKG), but if a validator does not update, their last announced session key is reused.

The reason for this is because I don't want some weird conditions during the DKG (DoS, network failure, censorship) causing a validator to be knocked offline for the whole next epoch. Since it would only make liveness during the DKG even more critical. I think the risk of reusing session keys for multiple epochs is very minimal, so this liveness risk is more significant.

Also, are we planning to run the DKG prior to the beginning of the epoch? Because otherwise the network will not be able to process transactions until the DKG finishes, right?

**Comment by batconjurer** [comment]
Ok, we can tie session key generation to validator account creation and take this approach. 

We are indeed running prior to the beginning of an epoch.
